### PR TITLE
Added help text on password change

### PR DESCRIPTION
**Pull request by madEng84**
As you can see in the screenshots, in this PR I have taken care of adding a help text to guide the user while writing the new password

Screenshot 2021-07-16 at 20 29 20

The writing is parameterized on the following settings:

- PASSWORD_MIN_LENGTH
- PASSWORD_MAX_CONSECUTIVE
- PASSWORD_MIN_LETTERS
- PASSWORD_MIN_LOWERCASE_LETTERS
- PASSWORD_MIN_UPPERCASE_LETTERS
- PASSWORD_MIN_NUMBERS
- PASSWORD_MIN_SYMBOLS
- PASSWORD_HISTORY_COUNT

If they are not set (or they are equal to 0) they will not be printed

Do you think it is useful?
Or do you think there is something else to add?

Obviously if there is something you want to change, please tell me

Thanks

### CODE REVIEW

**Comment by mpasternak** [comment]
Thanks, this is great! Please add a single test with the new functionality and I'll merge.

**Review by mpasternak — CHANGES_REQUESTED** [review]
Please add tests.

**Review by mpasternak — COMMENTED** [review]
Any ideas where that invisible character comes from, what is its purpose and maybe we could remove it? 

Also: do we still support Python 2.7?

**Comment by madEng84** [comment]
The problem is using the character •, I can replace it with "\u2022" to avoid adding coding utf-8 at the top of the file, but I don't know what's the better way.

as for the support for python2.7, unfortunately I'm integrating this library on a couple of projects with python 2.7 and django 1.11, too, and maybe I'm not the only one.
We can think of moving to a major release (2.0.0) which only supports py3 and django>=2.2
What do you think about it?


as soon as I have some time I add the tests
Thank you

**Comment by madEng84** [comment]
I'm closing this PR
I will make a cleaner request as soon as I have finished the reworks and when I have added the tests

Advice on how to improve this feature is welcome

**Pull request closed without merging**
