### PR TITLE
storing string in session instead of datetime to be able to use JSON …

### PR DESCRIPTION
**Pull request by Tossler**
…instead of pickle

### CODE REVIEW

**Comment by mpasternak** [comment]
This is a brillant idea, I'm going to merge it as soon as you provide some tests, especially a failing test with current behaviour.

**Comment by mpasternak** [comment]
Also, any particular reason why aren't we adding a custom serialise function to JSON serializer that would allow us to serialise datetime objects but we change the datetime to a string in every single place in the source instead? 

Just learn JSON serialiser how to treat datetime objects. Why aren't we using that solution in the first place?

**Comment by Tossler** [comment]
I know that Django already has DjangoJsonEncoder that is able to handle datetimes, and uses JSONSerializer from django.core.signing, but it doesn't specify the encoder in the serializer (and I couldn't find definition for decoder in django code - at least in django 1.11 - and decoder would somehow need to know that this string is datetime). I will do some helper function

**Comment by mpasternak** [comment]
Hi @Tossler , thank you for your comment, your patches and for taking time to contribute. 

From what I understand, what you want is to use a different SESSION_SERIALIZER. Good, pickle is insecure and we all know that. You wanted to use JSON. Good. Your JSON serializer does not know how to serialise datetime type. Good. 

What I think is, you should patch your serializer and teach it to serialise datetime objects. Most of the JSON serialisers around allow you to register your own serialisation functions for distinct types. See StackOverflow answers to following questions:

- https://stackoverflow.com/questions/11875770/how-to-overcome-datetime-datetime-not-json-serializable/36142844#36142844
- https://stackoverflow.com/questions/11875770/how-to-overcome-datetime-datetime-not-json-serializable

Thank you for your work again. My final verdict is I am against this patch and I am not willing to merge it. Please treat this neither personally nor emotionally. From what I know about JSON encoders, pickling and other stuff, adding a serialisation function for a new type is the way to go. Your fix is a workaround, but I don't think we're in position that needs quick hacks. 

Looking forward to hear from you.

**Pull request closed without merging**
